### ISSUE TITLE
Fix Lecture Cloud Native Previous and Next links.

### ISSUE THREAD

**Issue by intellits** [ibm-cloud-architecture/learning-cloudnative-101#109]
At the end of the **Lecture :: Cloud Native** `Previous` and `Next` topics needs to be updated as they are taking you respectively to `Perquisites` and `Cloud Native App Dev` of **Concept :: Cloud Native**.

**Comment by bkribbs15** [comment]
@intellits looks like I got a fix for it. Double check for me if you don't mind. Want to make sure I addressed the right issue.

**Comment by intellits** [comment]
Excellent. It works fine. 
Reagards,

Mohamed Belghiti
https://www.linkedin.com/in/mbelghiti
