### ISSUE TITLE
Update description of Jaeger in OpenShift & Kubernetes Activity

### ISSUE THREAD

**Issue by jesusmah** [ibm-cloud-architecture/learning-cloudnative-101#153]
Within the Distributed tracing section, there is an Activities table with some labs: https://cloudnative101.dev/electives/dist-trace/#activities

The description and link name (the link is actually correct) does not seem to match the activity topic.
That is, the activity is called "Jaeger in OpenShift & Kubernetes" while the description says "Implementing Istio on Kubernetes & OpenShift" and the link name is "Istio Kubernetes"

**Comment by bkribbs15** [comment]
@jesusmah thanks for finding that, I will put a fix in for it.
