### ISSUE TITLE
Unable to view the presentations

### ISSUE THREAD

**Issue by aliimran-pk** [ibm-cloud-architecture/learning-cloudnative-101#155]
![image](https://user-images.githubusercontent.com/35903658/89913746-860e6f80-dc0d-11ea-89c8-4fbbcce8b591.png)

Getting 404 error

**Comment by nc-hicbim** [comment]
More info:

The first 5 links on the course overview page have been changed and are now 404
https://cloudnative101.dev/course-overview/

Ex. 2. Containers
https://cloudnative101.dev/containers/
needs to be changed to
https://cloudnative101.dev/concepts/containers/
