### ISSUE TITLE
Request to add links to Cloud Architecture Center from Cloud-Native Developer Bootcamp course

### ISSUE THREAD

**Issue by Rivic** [ibm-cloud-architecture/learning-cloudnative-101#158]
This is a request to add links to the following architecture pages from the Resources section of this course:
IBM Garage Cloud-Native Developer Bootcamp
https://cloudnative101.dev/course-overview/

Would you please consider adding the following links?  Thank you!
https://www.ibm.com/cloud/architecture/architectures/cloud-native
https://www.ibm.com/cloud/architecture/architectures/public-cloud
https://www.ibm.com/cloud/architecture/architectures/private-cloud
https://www.ibm.com/cloud/architecture/architectures/devOpsArchitecture

**Comment by bkribbs15** [comment]
I can do that. @Rivic was there a specific place you wanted me to put them in the overview section?

**Comment by bkribbs15** [comment]
@Rivic https://cloudnative101.dev/resources/#ibm-architecture-center
