### ISSUE TITLE
startupProbe is missing in the list

### ISSUE THREAD

**Issue by imreveres** [ibm-cloud-architecture/learning-cloudnative-101#177]
I have found that:
https://cloudnative101.dev/lectures/kube-observability/#liveness-and-readiness-probes

...three options are named but only two listed:

> The kubelet can optionally perform and react to three kinds of probes on running Containers:
> 
> livenessProbe: Indicates whether the Container is running. Runs for the lifetime of the Container.
> 
> readinessProbe: Indicates whether the Container is ready to service requests. Only runs at start.

I guess the startupProbe is missing here.

(anyway: I am a big fan of cloudnative101.dev! really helpful!)

**Comment by bkribbs15** [comment]
Added it in, Thanks for finding that. @imreveres
